CREATE DATABASE Crow123;
USE Crow123;

CREATE TABLE usuarios (
    id INT PRIMARY KEY AUTO_INCREMENT,

    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(20) NOT NULL,

    nome VARCHAR(150) NOT NULL,

    estilo VARCHAR(150) NOT NULL,
    musica VARCHAR(150) NOT NULL,
    cantor VARCHAR(150) NOT NULL
)ENGINE = innoDB;